dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - test/tfun-test

