sudo: false
dist: trusty

language: cpp

matrix:
  include:
    - env: CC=gcc-6 CXX=g++-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake

    - env: CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          sources: llvm-toolchain-trusty-3.8
          packages:
            - cmake
            - clang-3.8

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - test/tfun-test

