sudo: false
dist: trusty

language: cpp

matrix:
  include:
    - env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake

    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - clang-3.8
            - libstdc++-6-dev

before_script:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}

script:
  - ./build.sh

